In [2]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import torch
import matplotlib.pyplot as plt

Singular Value Decomposition (SVD)

A = UD(V)^T

Where: 
    U is an orthogonal m x m matrix; its columns are the left-singular vectors of A.
    V is an orthogonal n x n matrix; its columns are the right-singular vectors of A.
    D is a diagonal m x n matrix; elements along its diagonal are the sigular values of A.

In [3]:
A = np.array([[-1,2],[3,-2],[5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [4]:
U, d, VT = np.linalg.svd(A)

In [5]:
U

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [6]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [7]:
d

array([8.66918448, 4.10429538])

In [8]:
np.diag(d)

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

In [9]:
D = np.concatenate((np.diag(d),[[0,0]]), axis=0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [10]:
np.dot(U, np.dot(D, VT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])

In [11]:
P = torch.tensor([[25, 2, -5], [3,-2, 1],[5,7,4.]])
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [12]:
U, S, Vh = torch.linalg.svd(P)

In [13]:
U

tensor([[-0.9757,  0.1823,  0.1214],
        [-0.0975,  0.1350, -0.9860],
        [-0.1961, -0.9739, -0.1140]])

In [14]:
import time
from PIL import Image

In [ ]:
! wget 